-- Generated by scripts/db/generate-dictionary.ts
-- Fallback schema renderer used when local pg_dump cannot connect to the server version.

CREATE TABLE bench.ground_truth (
  ground_truth_id uuid DEFAULT gen_random_uuid() NOT NULL,
  task_id uuid NOT NULL,
  scenario_id uuid,
  true_effect_id uuid,
  answer_key jsonb DEFAULT '{}'::jsonb NOT NULL,
  expected_verdict text NOT NULL,
  expected_lift numeric,
  tolerance numeric DEFAULT 0 NOT NULL,
  rationale text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE bench.ground_truth IS 'The canonical answer key for a benchmark task. For simulator-backed tasks it links to sim.true_effects so the scorer can compare an estimate against the known truth within tolerance.';
COMMENT ON COLUMN bench.ground_truth.ground_truth_id IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN bench.ground_truth.task_id IS 'The task this answer key belongs to (FK bench.tasks).';
COMMENT ON COLUMN bench.ground_truth.scenario_id IS 'Simulator scenario backing the task, if any (FK sim.scenarios).';
COMMENT ON COLUMN bench.ground_truth.true_effect_id IS 'The specific true effect this task is graded against (FK sim.true_effects).';
COMMENT ON COLUMN bench.ground_truth.answer_key IS 'Full expected answer as jsonb.';
COMMENT ON COLUMN bench.ground_truth.expected_verdict IS 'The expected high-level verdict (e.g. "block", "allow", "flag_waste").';
COMMENT ON COLUMN bench.ground_truth.expected_lift IS 'The expected incremental lift value, where the task scores a numeric estimate.';
COMMENT ON COLUMN bench.ground_truth.tolerance IS 'Allowed absolute deviation of an estimate from expected_lift to still pass.';
COMMENT ON COLUMN bench.ground_truth.rationale IS 'Explanation of why this is the correct answer.';
COMMENT ON COLUMN bench.ground_truth.created_at IS 'UTC creation timestamp.';

CREATE TABLE bench.results (
  result_id uuid DEFAULT gen_random_uuid() NOT NULL,
  run_id uuid NOT NULL,
  task_id uuid NOT NULL,
  passed boolean NOT NULL,
  score numeric DEFAULT 0 NOT NULL,
  unsafe_write_attempted boolean DEFAULT false NOT NULL,
  budget_cap_violation boolean DEFAULT false NOT NULL,
  hallucinated_id boolean DEFAULT false NOT NULL,
  evidence_coverage numeric DEFAULT 0 NOT NULL,
  rollback_coverage numeric DEFAULT 0 NOT NULL,
  notes ARRAY DEFAULT '{}'::text[] NOT NULL,
  output jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE bench.results IS 'The result of one task within one benchmark run. Captures the pass/fail verdict, score, and the safety counters that gate AdMatix release decisions.';
COMMENT ON COLUMN bench.results.result_id IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN bench.results.run_id IS 'The run this result belongs to (FK bench.runs).';
COMMENT ON COLUMN bench.results.task_id IS 'The task this result scores (FK bench.tasks).';
COMMENT ON COLUMN bench.results.passed IS 'True if the task passed.';
COMMENT ON COLUMN bench.results.score IS 'Continuous score in [0,1] for the task.';
COMMENT ON COLUMN bench.results.unsafe_write_attempted IS 'True if the system attempted an unsafe write (an automatic fail).';
COMMENT ON COLUMN bench.results.budget_cap_violation IS 'True if a budget cap was violated.';
COMMENT ON COLUMN bench.results.hallucinated_id IS 'True if the system referenced a non-existent entity id.';
COMMENT ON COLUMN bench.results.evidence_coverage IS 'Fraction of claims backed by valid evidence refs, in [0,1].';
COMMENT ON COLUMN bench.results.rollback_coverage IS 'Fraction of actions carrying a valid rollback, in [0,1].';
COMMENT ON COLUMN bench.results.notes IS 'Array of free-text notes on the result.';
COMMENT ON COLUMN bench.results.output IS 'Full system output for the task as jsonb, for inspection and replay.';
COMMENT ON COLUMN bench.results.created_at IS 'UTC timestamp the result was written.';

CREATE TABLE bench.runs (
  run_id uuid DEFAULT gen_random_uuid() NOT NULL,
  suite text NOT NULL,
  fixture_version text NOT NULL,
  code_version text NOT NULL,
  policy_version text NOT NULL,
  model text NOT NULL,
  summary jsonb DEFAULT '{}'::jsonb NOT NULL,
  pass_count integer DEFAULT 0 NOT NULL,
  fail_count integer DEFAULT 0 NOT NULL,
  started_at timestamp with time zone DEFAULT now() NOT NULL,
  finished_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE bench.runs IS 'One execution of a benchmark suite. Pins fixture, code, policy and model versions so results are reproducible and comparable across runs.';
COMMENT ON COLUMN bench.runs.run_id IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN bench.runs.suite IS 'Benchmark suite executed.';
COMMENT ON COLUMN bench.runs.fixture_version IS 'Pinned fixture/dataset version.';
COMMENT ON COLUMN bench.runs.code_version IS 'Pinned AdMatix code version (git sha or tag).';
COMMENT ON COLUMN bench.runs.policy_version IS 'Pinned policy version in force during the run.';
COMMENT ON COLUMN bench.runs.model IS 'Pinned model id used during the run.';
COMMENT ON COLUMN bench.runs.summary IS 'jsonb map of aggregate metric -> value for the run.';
COMMENT ON COLUMN bench.runs.pass_count IS 'Number of tasks that passed.';
COMMENT ON COLUMN bench.runs.fail_count IS 'Number of tasks that failed.';
COMMENT ON COLUMN bench.runs.started_at IS 'UTC timestamp the run began.';
COMMENT ON COLUMN bench.runs.finished_at IS 'UTC timestamp the run completed; null while in progress.';
COMMENT ON COLUMN bench.runs.created_at IS 'UTC timestamp the run row was written.';

CREATE TABLE bench.tasks (
  task_id uuid DEFAULT gen_random_uuid() NOT NULL,
  task_key text NOT NULL,
  suite text NOT NULL,
  kind task_kind NOT NULL,
  description text NOT NULL,
  fixture text NOT NULL,
  expected jsonb DEFAULT '{}'::jsonb NOT NULL,
  is_unsafe boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE bench.tasks IS 'A single benchmark task. Unsafe tasks (is_unsafe = true) MUST be blocked by the system to count as passed.';
COMMENT ON COLUMN bench.tasks.task_id IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN bench.tasks.task_key IS 'Stable human-readable task identifier, unique within a suite.';
COMMENT ON COLUMN bench.tasks.suite IS 'Benchmark suite the task belongs to.';
COMMENT ON COLUMN bench.tasks.kind IS 'Task category: audit | safety | evidence | state_diff | policy.';
COMMENT ON COLUMN bench.tasks.description IS 'Human-readable description of what the task tests.';
COMMENT ON COLUMN bench.tasks.fixture IS 'Identifier of the fixture/dataset the task runs against.';
COMMENT ON COLUMN bench.tasks.expected IS 'Expected outcome as jsonb, used to score a run.';
COMMENT ON COLUMN bench.tasks.is_unsafe IS 'True if the task represents an unsafe request the system must block.';
COMMENT ON COLUMN bench.tasks.created_at IS 'UTC creation timestamp.';
COMMENT ON COLUMN bench.tasks.updated_at IS 'UTC timestamp of the last mutation (maintained by trigger).';

CREATE TABLE sim.campaigns (
  sim_campaign_id uuid DEFAULT gen_random_uuid() NOT NULL,
  scenario_id uuid NOT NULL,
  sim_campaign_key text NOT NULL,
  name text NOT NULL,
  channel text NOT NULL,
  daily_budget numeric DEFAULT 0 NOT NULL,
  base_ctr numeric DEFAULT 0 NOT NULL,
  base_cvr numeric DEFAULT 0 NOT NULL,
  base_aov numeric DEFAULT 0 NOT NULL,
  params jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE sim.campaigns IS 'A synthetic campaign within a simulation scenario. Carries the base-rate parameters (CTR, CVR, AOV) the simulator draws events from.';
COMMENT ON COLUMN sim.campaigns.sim_campaign_id IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN sim.campaigns.scenario_id IS 'Parent scenario (FK sim.scenarios).';
COMMENT ON COLUMN sim.campaigns.sim_campaign_key IS 'Human-readable campaign key, unique within a scenario.';
COMMENT ON COLUMN sim.campaigns.name IS 'Human-readable campaign name.';
COMMENT ON COLUMN sim.campaigns.channel IS 'Simulated channel (search, social, display, ...).';
COMMENT ON COLUMN sim.campaigns.daily_budget IS 'Simulated daily budget.';
COMMENT ON COLUMN sim.campaigns.base_ctr IS 'Baseline click-through rate the simulator draws from.';
COMMENT ON COLUMN sim.campaigns.base_cvr IS 'Baseline conversion rate the simulator draws from.';
COMMENT ON COLUMN sim.campaigns.base_aov IS 'Baseline average order value the simulator draws from.';
COMMENT ON COLUMN sim.campaigns.params IS 'Additional campaign-specific simulation parameters as jsonb.';
COMMENT ON COLUMN sim.campaigns.created_at IS 'UTC creation timestamp.';

CREATE TABLE sim.events (
  sim_event_id bigint NOT NULL,
  scenario_id uuid NOT NULL,
  sim_campaign_id uuid NOT NULL,
  true_effect_id uuid,
  event_type event_type NOT NULL,
  treatment_arm treatment_arm NOT NULL,
  sim_day integer NOT NULL,
  event_ts timestamp with time zone NOT NULL,
  user_key text NOT NULL,
  quantity numeric DEFAULT 1 NOT NULL,
  spend numeric DEFAULT 0 NOT NULL,
  revenue numeric DEFAULT 0 NOT NULL,
  attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE sim.events IS 'The event stream produced by the simulator: impressions, clicks, conversions and spend, each tagged with the treatment arm. This is the observable data the verifier consumes; the true effect behind it lives in sim.true_effects.';
COMMENT ON COLUMN sim.events.sim_event_id IS 'Surrogate primary key (identity).';
COMMENT ON COLUMN sim.events.scenario_id IS 'Parent scenario (FK sim.scenarios).';
COMMENT ON COLUMN sim.events.sim_campaign_id IS 'Simulated campaign the event belongs to (FK sim.campaigns).';
COMMENT ON COLUMN sim.events.true_effect_id IS 'The true effect that generated this event, if any (FK sim.true_effects). Used only by the scorer.';
COMMENT ON COLUMN sim.events.event_type IS 'Event type: impression | click | conversion | spend.';
COMMENT ON COLUMN sim.events.treatment_arm IS 'Experimental arm of the user: treatment | control | holdout.';
COMMENT ON COLUMN sim.events.sim_day IS 'Simulated day index within the scenario horizon.';
COMMENT ON COLUMN sim.events.event_ts IS 'UTC timestamp of the simulated event.';
COMMENT ON COLUMN sim.events.user_key IS 'Synthetic user identifier.';
COMMENT ON COLUMN sim.events.quantity IS 'Event quantity (1 per discrete event; supports fractional credit).';
COMMENT ON COLUMN sim.events.spend IS 'Spend attributed to the event.';
COMMENT ON COLUMN sim.events.revenue IS 'Revenue attributed to the event.';
COMMENT ON COLUMN sim.events.attributes IS 'Additional simulated event attributes as jsonb.';
COMMENT ON COLUMN sim.events.created_at IS 'UTC timestamp the event row was written.';

CREATE TABLE sim.scenarios (
  scenario_id uuid DEFAULT gen_random_uuid() NOT NULL,
  scenario_key text NOT NULL,
  name text NOT NULL,
  description text,
  random_seed bigint NOT NULL,
  horizon_days integer DEFAULT 30 NOT NULL,
  config jsonb DEFAULT '{}'::jsonb NOT NULL,
  config_hash character NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE sim.scenarios IS 'A configured simulation scenario. random_seed and config_hash make every scenario fully reproducible.';
COMMENT ON COLUMN sim.scenarios.scenario_id IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN sim.scenarios.scenario_key IS 'Stable human-readable scenario identifier.';
COMMENT ON COLUMN sim.scenarios.name IS 'Human-readable scenario name.';
COMMENT ON COLUMN sim.scenarios.description IS 'Description of what the scenario exercises.';
COMMENT ON COLUMN sim.scenarios.random_seed IS 'RNG seed; fixing it makes the scenario deterministic and reproducible.';
COMMENT ON COLUMN sim.scenarios.horizon_days IS 'Number of simulated days the scenario runs.';
COMMENT ON COLUMN sim.scenarios.config IS 'Full scenario configuration as jsonb (market params, noise, agent behaviours).';
COMMENT ON COLUMN sim.scenarios.config_hash IS 'SHA-256 (hex) of the config, for integrity and reproducibility checks.';
COMMENT ON COLUMN sim.scenarios.created_at IS 'UTC creation timestamp.';

CREATE TABLE sim.true_effects (
  true_effect_id uuid DEFAULT gen_random_uuid() NOT NULL,
  scenario_id uuid NOT NULL,
  sim_campaign_id uuid NOT NULL,
  intervention_key text NOT NULL,
  metric text NOT NULL,
  true_incremental_lift numeric NOT NULL,
  true_lift_pct numeric,
  true_baseline numeric,
  effect_start_day integer DEFAULT 0 NOT NULL,
  effect_end_day integer,
  noise_sd numeric DEFAULT 0 NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE sim.true_effects IS 'The hidden ground-truth incremental lift for each simulated intervention -- the answer key. The verification pipeline must NOT read this table; only the scorer reads it to grade the verifier estimate against truth.';
COMMENT ON COLUMN sim.true_effects.true_effect_id IS 'Surrogate primary key (UUID v4).';
COMMENT ON COLUMN sim.true_effects.scenario_id IS 'Parent scenario (FK sim.scenarios).';
COMMENT ON COLUMN sim.true_effects.sim_campaign_id IS 'Simulated campaign the effect applies to (FK sim.campaigns).';
COMMENT ON COLUMN sim.true_effects.intervention_key IS 'Identifier of the intervention whose true effect this row records (e.g. "budget_+20pct").';
COMMENT ON COLUMN sim.true_effects.metric IS 'The metric the effect is expressed on (conversions, revenue, ...).';
COMMENT ON COLUMN sim.true_effects.true_incremental_lift IS 'The true incremental lift in absolute metric units. The ground truth.';
COMMENT ON COLUMN sim.true_effects.true_lift_pct IS 'The true incremental lift as a percentage of baseline.';
COMMENT ON COLUMN sim.true_effects.true_baseline IS 'The true counterfactual baseline (metric value with no intervention).';
COMMENT ON COLUMN sim.true_effects.effect_start_day IS 'Simulated day the effect begins.';
COMMENT ON COLUMN sim.true_effects.effect_end_day IS 'Simulated day the effect ends; null if it persists to the horizon.';
COMMENT ON COLUMN sim.true_effects.noise_sd IS 'Standard deviation of the noise the simulator adds around the true effect.';
COMMENT ON COLUMN sim.true_effects.notes IS 'Optional notes on how the effect was configured.';
COMMENT ON COLUMN sim.true_effects.created_at IS 'UTC creation timestamp.';

CREATE TABLE warehouse.admatix_accounts_seed (
  account_business_key text,
  tenant_id uuid,
  platform text,
  external_account_id text,
  account_name text,
  currency text,
  timezone text,
  is_active boolean
);


CREATE TABLE warehouse.admatix_ad_sets_seed (
  ad_set_business_key text,
  campaign_business_key text,
  external_ad_set_id text,
  ad_set_name text,
  status text,
  bid_strategy text,
  daily_budget numeric,
  optimization_goal text
);


CREATE TABLE warehouse.admatix_campaigns_seed (
  campaign_business_key text,
  account_business_key text,
  platform text,
  external_campaign_id text,
  campaign_name text,
  objective text,
  status text,
  daily_budget numeric,
  lifetime_budget numeric,
  start_date date,
  end_date date,
  bid_strategy text
);


CREATE TABLE warehouse.admatix_creative_metrics_seed (
  platform text,
  external_account_id text,
  campaign_external_id text,
  creative_external_id text,
  metric_date date,
  spend numeric,
  impressions bigint,
  clicks bigint,
  conversions numeric,
  frequency numeric,
  _source text,
  _batch_id text,
  _row_hash double precision
);


CREATE TABLE warehouse.admatix_creatives_seed (
  creative_business_key text,
  campaign_business_key text,
  ad_set_business_key text,
  external_creative_id text,
  creative_format text,
  headline text,
  body_text text,
  final_url text,
  policy_status text,
  status text
);


CREATE TABLE warehouse.admatix_first_party_orders_seed (
  external_account_id text,
  order_external_id text,
  order_ts timestamp with time zone,
  customer_key text,
  revenue numeric,
  gross_margin numeric,
  currency text,
  channel text,
  is_new_customer integer,
  _source text,
  _batch_id text,
  _row_hash double precision
);


CREATE TABLE warehouse.admatix_platform_metrics_seed (
  platform text,
  external_account_id text,
  campaign_external_id text,
  metric_date date,
  spend numeric,
  impressions bigint,
  clicks bigint,
  conversions numeric,
  platform_revenue numeric,
  currency text,
  _source text,
  _batch_id text,
  _row_hash integer
);


CREATE TABLE warehouse.bronze_avazu (
  bronze_id bigint,
  ad_id text,
  click smallint,
  hour_raw text,
  c1 text,
  banner_pos text,
  site_id text,
  site_domain text,
  site_category text,
  app_id text,
  app_domain text,
  app_category text,
  device_id text,
  device_ip text,
  device_model text,
  device_type text,
  device_conn_type text,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.bronze_creative_metrics_fixture (
  bronze_id bigint,
  platform text,
  external_account_id text,
  campaign_external_id text,
  creative_external_id text,
  metric_date date,
  spend double precision,
  impressions bigint,
  clicks bigint,
  conversions double precision,
  frequency double precision,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.bronze_criteo_uplift (
  bronze_id bigint,
  f0 double precision,
  f1 double precision,
  f2 double precision,
  f3 double precision,
  f4 double precision,
  f5 double precision,
  f6 double precision,
  f7 double precision,
  f8 double precision,
  f9 double precision,
  f10 double precision,
  f11 double precision,
  treatment smallint,
  conversion smallint,
  visit smallint,
  exposure smallint,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.bronze_first_party_orders (
  bronze_id bigint,
  external_account_id text,
  order_external_id text,
  order_ts timestamp with time zone,
  customer_key text,
  revenue double precision,
  gross_margin double precision,
  currency text,
  channel text,
  is_new_customer smallint,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.bronze_hillstrom (
  bronze_id bigint,
  recency integer,
  history_segment text,
  history double precision,
  mens smallint,
  womens smallint,
  zip_code text,
  newbie smallint,
  channel text,
  segment text,
  visit smallint,
  conversion smallint,
  spend double precision,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.bronze_ipinyou (
  bronze_id bigint,
  bid_id text,
  log_type text,
  timestamp_raw text,
  ipinyou_id text,
  user_agent text,
  ip text,
  region text,
  city text,
  ad_exchange text,
  domain text,
  url text,
  ad_slot_id text,
  ad_slot_width integer,
  ad_slot_height integer,
  ad_slot_floor double precision,
  bidding_price double precision,
  paying_price double precision,
  creative_id text,
  advertiser_id text,
  is_click smallint,
  is_conversion smallint,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.bronze_platform_metrics (
  bronze_id bigint,
  platform text,
  external_account_id text,
  campaign_external_id text,
  metric_date date,
  spend double precision,
  impressions bigint,
  clicks bigint,
  conversions double precision,
  platform_revenue double precision,
  currency text,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.bronze_sim_events (
  bronze_id bigint,
  scenario_id text,
  sim_campaign_id text,
  event_type text,
  event_ts timestamp with time zone,
  user_key text,
  treatment_arm text,
  spend double precision,
  revenue double precision,
  raw jsonb,
  _loaded_at timestamp with time zone,
  _source text,
  _batch_id text,
  _row_hash character
);


CREATE TABLE warehouse.dim_account (
  account_key bigint,
  account_business_key text,
  tenant_id uuid,
  platform ad_platform,
  external_account_id text,
  account_name text,
  currency character,
  timezone text,
  is_active boolean,
  updated_at timestamp with time zone
);


CREATE TABLE warehouse.dim_ad_set (
  ad_set_key bigint,
  ad_set_business_key text,
  campaign_key bigint,
  external_ad_set_id text,
  ad_set_name text,
  status entity_status,
  bid_strategy text,
  daily_budget numeric,
  optimization_goal text,
  valid_from timestamp without time zone,
  valid_to timestamp with time zone,
  is_current boolean,
  row_hash character
);


CREATE TABLE warehouse.dim_ad_set_snapshot (
  ad_set_business_key text,
  campaign_business_key text,
  external_ad_set_id text,
  ad_set_name text,
  status entity_status,
  bid_strategy text,
  daily_budget numeric,
  optimization_goal text,
  is_current boolean,
  row_hash character,
  dbt_scd_id text,
  dbt_updated_at timestamp without time zone,
  valid_from timestamp without time zone,
  valid_to timestamp without time zone
);


CREATE TABLE warehouse.dim_audience (
  audience_key bigint,
  audience_business_key text,
  audience_name text,
  audience_type text,
  platform ad_platform,
  size_estimate bigint,
  description text
);


CREATE TABLE warehouse.dim_campaign (
  campaign_key bigint,
  campaign_business_key text,
  account_key bigint,
  platform ad_platform,
  external_campaign_id text,
  campaign_name text,
  objective text,
  status entity_status,
  daily_budget numeric,
  lifetime_budget numeric,
  start_date date,
  end_date date,
  valid_from timestamp without time zone,
  valid_to timestamp with time zone,
  is_current boolean,
  row_hash character
);


CREATE TABLE warehouse.dim_campaign_snapshot (
  campaign_business_key text,
  account_business_key text,
  platform ad_platform,
  external_campaign_id text,
  campaign_name text,
  objective text,
  status entity_status,
  daily_budget numeric,
  lifetime_budget numeric,
  start_date date,
  end_date date,
  bid_strategy text,
  is_current boolean,
  row_hash character,
  dbt_scd_id text,
  dbt_updated_at timestamp without time zone,
  valid_from timestamp without time zone,
  valid_to timestamp without time zone
);


CREATE TABLE warehouse.dim_creative (
  creative_key bigint,
  creative_business_key text,
  campaign_key bigint,
  ad_set_key bigint,
  external_creative_id text,
  creative_format text,
  headline text,
  body_text text,
  final_url text,
  policy_status text,
  status entity_status,
  valid_from timestamp without time zone,
  valid_to timestamp with time zone,
  is_current boolean,
  row_hash character
);


CREATE TABLE warehouse.dim_creative_snapshot (
  creative_business_key text,
  campaign_business_key text,
  ad_set_business_key text,
  external_creative_id text,
  creative_format text,
  headline text,
  body_text text,
  final_url text,
  policy_status text,
  status entity_status,
  is_current boolean,
  row_hash character,
  dbt_scd_id text,
  dbt_updated_at timestamp without time zone,
  valid_from timestamp without time zone,
  valid_to timestamp without time zone
);


CREATE TABLE warehouse.dim_date (
  date_key integer,
  full_date date,
  day_of_week smallint,
  day_name text,
  day_of_month smallint,
  day_of_year smallint,
  week_of_year smallint,
  iso_week smallint,
  month_number smallint,
  month_name text,
  quarter smallint,
  year smallint,
  is_weekend boolean,
  is_month_start boolean,
  is_month_end boolean
);


CREATE TABLE warehouse.dim_device (
  device_key smallint,
  device_business_key text,
  device_type text,
  device_category text,
  operating_system text
);


CREATE TABLE warehouse.dim_geo (
  geo_key bigint,
  geo_business_key text,
  country_code character,
  country_name text,
  region text,
  region_code text,
  city text,
  metro_code text,
  postal_code text
);


CREATE TABLE warehouse.dim_platform (
  platform_key smallint,
  platform_code ad_platform,
  platform_name text,
  platform_family text,
  is_truth_source boolean
);


CREATE TABLE warehouse.fct_campaign_action (
  campaign_action_id bigint,
  proposed_date_key integer,
  decided_date_key integer,
  measured_date_key integer,
  account_key bigint,
  campaign_key bigint,
  platform_key smallint,
  h0_packet_id uuid,
  proposed_action_id uuid,
  tx_id text,
  action_type action_type,
  risk_level risk_level,
  policy_result policy_result,
  approval_decision approval_decision,
  estimated_impact numeric,
  realized_impact numeric,
  was_measured boolean,
  _source text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.fct_clicks (
  click_id bigint,
  date_key integer,
  account_key bigint,
  campaign_key bigint,
  ad_set_key bigint,
  creative_key bigint,
  platform_key smallint,
  geo_key bigint,
  audience_key bigint,
  device_key smallint,
  click_ts timestamp with time zone,
  clicks bigint,
  cost numeric,
  _source text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.fct_conversions (
  conversion_id bigint,
  date_key integer,
  account_key bigint,
  campaign_key bigint,
  ad_set_key bigint,
  creative_key bigint,
  platform_key smallint,
  geo_key bigint,
  audience_key bigint,
  device_key smallint,
  conversion_ts timestamp with time zone,
  conversions numeric,
  revenue numeric,
  is_first_party boolean,
  attribution_model text,
  _source text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.fct_impressions (
  impression_id bigint,
  date_key integer,
  account_key bigint,
  campaign_key bigint,
  ad_set_key bigint,
  creative_key bigint,
  platform_key smallint,
  geo_key bigint,
  audience_key bigint,
  device_key smallint,
  impression_ts timestamp with time zone,
  impressions bigint,
  cost numeric,
  _source text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.fct_outcome (
  outcome_id bigint,
  date_key integer,
  account_key bigint,
  campaign_key bigint,
  platform_key smallint,
  h0_packet_id uuid,
  tx_id text,
  success_metric text,
  baseline_value numeric,
  observed_value numeric,
  delta_pct numeric,
  estimated_lift numeric,
  lift_ci_low numeric,
  lift_ci_high numeric,
  ground_truth_lift numeric,
  causal_status causal_status,
  passed boolean,
  _source text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.fct_spend_daily (
  spend_daily_id bigint,
  date_key integer,
  account_key bigint,
  campaign_key bigint,
  ad_set_key bigint,
  platform_key smallint,
  spend numeric,
  impressions bigint,
  clicks bigint,
  conversions numeric,
  platform_revenue numeric,
  currency character,
  _source text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.mart_agent_safety (
  run_id text,
  agent_id text,
  tenant_id uuid,
  workflow_id text,
  tx_id text,
  step text,
  model text,
  policy_version text,
  risk_level text,
  status text,
  blocked_reason text,
  duration_ms integer,
  created_at timestamp with time zone,
  policy_decisions bigint,
  blocked_policy_decisions bigint,
  suite text,
  benchmark_score numeric,
  benchmark_passed boolean,
  unsafe_write_attempted boolean,
  budget_cap_violation boolean,
  hallucinated_id boolean,
  evidence_coverage numeric,
  rollback_coverage numeric,
  policy_block_rate numeric,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.mart_campaign_performance (
  date_key integer,
  metric_date date,
  account_key bigint,
  tenant_id uuid,
  platform ad_platform,
  external_account_id text,
  account_name text,
  platform_key smallint,
  platform_name text,
  platform_family text,
  campaign_key bigint,
  campaign_business_key text,
  external_campaign_id text,
  campaign_name text,
  objective text,
  campaign_status entity_status,
  currency character,
  spend numeric,
  impressions bigint,
  clicks bigint,
  platform_conversions numeric,
  first_party_orders bigint,
  platform_revenue numeric,
  first_party_revenue numeric,
  gross_margin numeric,
  new_customers bigint,
  ctr numeric,
  cvr numeric,
  platform_roas numeric,
  first_party_roas numeric,
  cac numeric,
  mer numeric,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.mart_evidence_coverage (
  date_key integer,
  metric_date date,
  tenant_id uuid,
  tenant_slug text,
  tenant_name text,
  proposed_action_count bigint,
  complete_h0_action_count bigint,
  policy_decision_count bigint,
  blocked_action_count bigint,
  allowed_action_count bigint,
  needs_approval_action_count bigint,
  ledger_visible_action_count bigint,
  coverage_pct numeric,
  ledger_visibility_pct numeric,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.mart_pacing (
  date_key integer,
  metric_date date,
  account_key bigint,
  tenant_id uuid,
  platform ad_platform,
  account_name text,
  platform_key smallint,
  platform_name text,
  campaign_key bigint,
  campaign_business_key text,
  external_campaign_id text,
  campaign_name text,
  campaign_status entity_status,
  daily_budget numeric,
  lifetime_budget numeric,
  start_date date,
  end_date date,
  spend numeric,
  cumulative_spend numeric,
  elapsed_reporting_days integer,
  planned_spend_to_date numeric,
  pacing_variance numeric,
  pacing_ratio numeric,
  days_remaining integer,
  projected_total_spend numeric,
  projected_overspend numeric,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.mart_verification (
  date_key integer,
  measured_date date,
  h0_packet_id uuid,
  tx_id text,
  account_key bigint,
  tenant_id uuid,
  platform ad_platform,
  account_name text,
  platform_key smallint,
  platform_name text,
  campaign_key bigint,
  campaign_business_key text,
  external_campaign_id text,
  campaign_name text,
  proposed_action_id uuid,
  action_type action_type,
  policy_result policy_result,
  approval_decision approval_decision,
  success_metric text,
  baseline_value numeric,
  observed_value numeric,
  delta_pct numeric,
  estimated_lift numeric,
  lift_ci_low numeric,
  lift_ci_high numeric,
  ground_truth_lift numeric,
  method text,
  causal_status causal_status,
  verdict text,
  passed boolean,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.mart_waste (
  date_key integer,
  metric_date date,
  account_key bigint,
  tenant_id uuid,
  platform ad_platform,
  account_name text,
  platform_key smallint,
  platform_name text,
  campaign_key bigint,
  campaign_business_key text,
  external_campaign_id text,
  campaign_name text,
  creative_key bigint,
  external_creative_id text,
  creative_format text,
  waste_type text,
  waste_entity_id text,
  wasted_spend numeric,
  conversions_in_window numeric,
  lookback_days integer,
  dead_keyword_signal_available boolean,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.silver_auctions (
  silver_auction_id bigint,
  auction_key text,
  auction_ts_raw text,
  creative_key text,
  advertiser_key text,
  region text,
  city text,
  ad_exchange text,
  domain text,
  ad_slot_id text,
  ad_slot_width integer,
  ad_slot_height integer,
  floor_price numeric,
  bid_price numeric,
  paid_price numeric,
  is_click smallint,
  is_conversion smallint,
  _source text,
  _batch_id text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.silver_campaign_daily (
  silver_campaign_daily_id bigint,
  metric_date date,
  platform ad_platform,
  account_key text,
  campaign_key text,
  spend numeric,
  impressions bigint,
  clicks bigint,
  conversions numeric,
  platform_revenue numeric,
  currency character,
  _source text,
  _batch_id text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.silver_conversions (
  silver_conversion_id bigint,
  conversion_key text,
  account_key text,
  campaign_key text,
  creative_key text,
  conversion_ts timestamp with time zone,
  customer_key text,
  revenue numeric,
  is_first_party boolean,
  attribution_model text,
  _source text,
  _batch_id text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.silver_creative_daily (
  silver_creative_daily_id bigint,
  metric_date date,
  platform ad_platform,
  account_key text,
  campaign_key text,
  creative_key text,
  spend numeric,
  impressions bigint,
  clicks bigint,
  conversions numeric,
  frequency numeric,
  _source text,
  _batch_id text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.silver_first_party_daily (
  silver_first_party_daily_id bigint,
  metric_date date,
  account_key text,
  revenue numeric,
  orders bigint,
  gross_margin numeric,
  new_customers bigint,
  currency character,
  _source text,
  _batch_id text,
  _loaded_at timestamp with time zone
);


CREATE TABLE warehouse.silver_treatment_assignment (
  silver_treatment_assignment_id bigint,
  experiment_key text,
  unit_key text,
  account_key text,
  campaign_key text,
  treatment_arm text,
  is_treated boolean,
  assigned_at timestamp with time zone,
  assignment_source text,
  _source text,
  _batch_id text,
  _loaded_at timestamp with time zone
);

