admatix_supabase:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      dbname: "{{ env_var('SUPABASE_DB_URL') | as_native }}"
      host: "{{ env_var('SUPABASE_DB_URL') | as_native }}"
      user: "{{ env_var('SUPABASE_DB_URL') | as_native }}"
      pass: "{{ env_var('SUPABASE_DB_URL') | as_native }}"
      port: 5432
      schema: warehouse
      sslmode: require

