BEGIN;

-- ============================================================================
-- AdMatix Data Layer -- Part 1: ledger schema
-- Tamper-evident, append-only event log + Merkle anchoring.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS ledger;

COMMENT ON SCHEMA ledger IS
  'Tamper-evident, append-only audit ledger. Every governance-relevant event (proposal, gate decision, approval, execution diff, measurement, reflection, flag) is hash-chained here. UPDATE and DELETE are revoked and blocked by trigger. Merkle anchors provide external verifiability.';

-- ----------------------------------------------------------------------------
-- Enum: ledger.event_type -- the kind of governance event recorded.
-- ----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_type t
      JOIN pg_namespace n ON n.oid = t.typnamespace
     WHERE n.nspname = 'ledger'
       AND t.typname = 'event_type'
  ) THEN
    CREATE TYPE ledger.event_type AS ENUM (
      'proposal',        -- an H0 packet / proposed action was created
      'gate_decision',   -- a policy gate allowed/blocked/escalated an action
      'approval',        -- a human approval or rejection receipt
      'execution_diff',  -- a dry-run before/after preview was produced
      'measurement',     -- an outcome measurement was recorded
      'reflection',      -- a reflect-step learning was recorded
      'flag'             -- a manual or automated integrity/anomaly flag
    );
  END IF;
END;
$$;

COMMENT ON TYPE ledger.event_type IS
  'Classifies a ledger.action_events row: proposal | gate_decision | approval | execution_diff | measurement | reflection | flag.';

-- ----------------------------------------------------------------------------
-- Enum: ledger.workflow_step -- which phase of plan/activate/measure/reflect.
-- ----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_type t
      JOIN pg_namespace n ON n.oid = t.typnamespace
     WHERE n.nspname = 'ledger'
       AND t.typname = 'workflow_step'
  ) THEN
    CREATE TYPE ledger.workflow_step AS ENUM (
      'plan',      -- planning / proposal generation
      'activate',  -- dry-run activation and gating
      'measure',   -- outcome measurement
      'reflect'    -- post-hoc reflection / learning
    );
  END IF;
END;
$$;

COMMENT ON TYPE ledger.workflow_step IS
  'The plan/activate/measure/reflect phase an event belongs to. Mirrors WorkflowStep in @admatix/schemas.';

-- ----------------------------------------------------------------------------
-- Table: ledger.action_events
-- Grain: exactly one row per governance event. Append-only, hash-chained.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ledger.action_events (
  event_id        text                 NOT NULL,
  seq             bigserial            NOT NULL,
  tx_id           text                 NOT NULL,
  workflow_id     text                 NOT NULL,
  trace_id        text                 NOT NULL,
  tenant_id       text                 NOT NULL,
  event_type      ledger.event_type    NOT NULL,
  step            ledger.workflow_step NOT NULL,
  actor_agent_id  text                 NOT NULL,
  subject_id      text,
  payload         jsonb                NOT NULL DEFAULT '{}'::jsonb,
  payload_hash    char(64)             NOT NULL,
  prev_hash       char(64)             NOT NULL,
  entry_hash      char(64)             NOT NULL,
  signature       text,
  created_at      timestamptz          NOT NULL DEFAULT now(),

  CONSTRAINT pk_action_events            PRIMARY KEY (event_id),
  CONSTRAINT uq_action_events_seq        UNIQUE (seq),
  CONSTRAINT uq_action_events_entry_hash UNIQUE (entry_hash),
  CONSTRAINT ck_action_events_payload_hash_hex
    CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_action_events_prev_hash_hex
    CHECK (prev_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_action_events_entry_hash_hex
    CHECK (entry_hash ~ '^[0-9a-f]{64}$')
);

COMMENT ON TABLE ledger.action_events IS
  'Append-only hash-chained event ledger. One row per governance event. seq gives monotonic chain order; entry_hash chains each row to its predecessor via prev_hash. UPDATE/DELETE are revoked and trigger-blocked.';

COMMENT ON COLUMN ledger.action_events.event_id IS
  'Primary key. ULID rendered as text (26-char Crockford base32), generated by the application. Sortable by creation time.';
COMMENT ON COLUMN ledger.action_events.seq IS
  'Monotonic chain order (bigserial). Defines the canonical hash-chain sequence; ordering is strictly increasing.';
COMMENT ON COLUMN ledger.action_events.tx_id IS
  'AdMatix transaction id tying together task, cost, route, trace and handoff records. Never null; preserved end-to-end.';
COMMENT ON COLUMN ledger.action_events.workflow_id IS
  'Identifier of the plan/activate/measure/reflect workflow instance this event belongs to.';
COMMENT ON COLUMN ledger.action_events.trace_id IS
  'Distributed trace id (Langfuse/OpenTelemetry) for cross-system correlation.';
COMMENT ON COLUMN ledger.action_events.tenant_id IS
  'Owning tenant. Denormalised into the ledger so a tenant slice of the chain can be exported and verified independently.';
COMMENT ON COLUMN ledger.action_events.event_type IS
  'Kind of event: proposal | gate_decision | approval | execution_diff | measurement | reflection | flag.';
COMMENT ON COLUMN ledger.action_events.step IS
  'Workflow phase: plan | activate | measure | reflect.';
COMMENT ON COLUMN ledger.action_events.actor_agent_id IS
  'Identifier of the agent or human actor that produced the event (e.g. "policy-guard", "user:uuid").';
COMMENT ON COLUMN ledger.action_events.subject_id IS
  'Identifier of the entity the event is about (h0_packet id, proposed_action id, etc.). Nullable for system-level events.';
COMMENT ON COLUMN ledger.action_events.payload IS
  'Full event payload as jsonb. Immutable. The canonical, hashable record of what happened.';
COMMENT ON COLUMN ledger.action_events.payload_hash IS
  'SHA-256 (hex, 64 chars) of the canonicalised payload. Computed by trigger via admatix_sha256_jsonb(payload).';
COMMENT ON COLUMN ledger.action_events.prev_hash IS
  'entry_hash of the immediately preceding row in seq order. The genesis row uses 64 zero characters. Set by trigger.';
COMMENT ON COLUMN ledger.action_events.entry_hash IS
  'SHA-256 of the chain material (prev_hash || event_id || tx_id || event_type || step || payload_hash || created_at). Set by trigger.';
COMMENT ON COLUMN ledger.action_events.signature IS
  'Optional detached cryptographic signature over entry_hash (e.g. Ed25519, base64). Null when signing is not configured.';
COMMENT ON COLUMN ledger.action_events.created_at IS
  'UTC timestamp the event was written. Part of the chain material; immutable.';

-- Indexes: every common filter column gets an index.
CREATE INDEX IF NOT EXISTS idx_action_events_tx_id        ON ledger.action_events (tx_id);
CREATE INDEX IF NOT EXISTS idx_action_events_workflow_id  ON ledger.action_events (workflow_id);
CREATE INDEX IF NOT EXISTS idx_action_events_trace_id     ON ledger.action_events (trace_id);
CREATE INDEX IF NOT EXISTS idx_action_events_tenant_id    ON ledger.action_events (tenant_id);
CREATE INDEX IF NOT EXISTS idx_action_events_event_type   ON ledger.action_events (event_type);
CREATE INDEX IF NOT EXISTS idx_action_events_step         ON ledger.action_events (step);
CREATE INDEX IF NOT EXISTS idx_action_events_subject_id   ON ledger.action_events (subject_id);
CREATE INDEX IF NOT EXISTS idx_action_events_actor        ON ledger.action_events (actor_agent_id);
CREATE INDEX IF NOT EXISTS idx_action_events_created_at   ON ledger.action_events (created_at);
CREATE INDEX IF NOT EXISTS idx_action_events_tenant_seq   ON ledger.action_events (tenant_id, seq);
CREATE INDEX IF NOT EXISTS idx_action_events_payload_gin  ON ledger.action_events USING gin (payload jsonb_path_ops);

COMMENT ON INDEX ledger.idx_action_events_tenant_seq IS
  'Composite index supporting per-tenant chain export and verification in seq order.';
COMMENT ON INDEX ledger.idx_action_events_payload_gin IS
  'GIN index on the jsonb payload for containment queries (@>) used by the verification dashboard.';

-- ----------------------------------------------------------------------------
-- Table: ledger.merkle_anchors
-- Periodic anchoring of a contiguous range of action_events into a Merkle root.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ledger.merkle_anchors (
  anchor_id        bigint        GENERATED ALWAYS AS IDENTITY,
  from_seq         bigint        NOT NULL,
  to_seq           bigint        NOT NULL,
  merkle_root      char(64)      NOT NULL,
  event_count      integer       NOT NULL,
  anchored_at      timestamptz   NOT NULL DEFAULT now(),
  external_anchor  text,

  CONSTRAINT pk_merkle_anchors          PRIMARY KEY (anchor_id),
  CONSTRAINT uq_merkle_anchors_range    UNIQUE (from_seq, to_seq),
  CONSTRAINT ck_merkle_anchors_range    CHECK (to_seq >= from_seq),
  CONSTRAINT ck_merkle_anchors_count    CHECK (event_count = to_seq - from_seq + 1),
  CONSTRAINT ck_merkle_anchors_root_hex CHECK (merkle_root ~ '^[0-9a-f]{64}$')
);

COMMENT ON TABLE ledger.merkle_anchors IS
  'Periodic Merkle anchoring of contiguous action_events ranges. Each row commits a verifiable digest of [from_seq, to_seq]. external_anchor optionally records an off-system commitment (blockchain tx, RFC-3161 timestamp) for independent verification.';

COMMENT ON COLUMN ledger.merkle_anchors.anchor_id IS 'Surrogate primary key (identity).';
COMMENT ON COLUMN ledger.merkle_anchors.from_seq IS
  'Inclusive lower bound: the smallest action_events.seq covered by this anchor.';
COMMENT ON COLUMN ledger.merkle_anchors.to_seq IS
  'Inclusive upper bound: the largest action_events.seq covered by this anchor.';
COMMENT ON COLUMN ledger.merkle_anchors.merkle_root IS
  'SHA-256 (hex, 64 chars) Merkle root computed over the entry_hash values of all events in [from_seq, to_seq].';
COMMENT ON COLUMN ledger.merkle_anchors.event_count IS
  'Number of events covered. Constrained to equal to_seq - from_seq + 1.';
COMMENT ON COLUMN ledger.merkle_anchors.anchored_at IS 'UTC timestamp the anchor was computed and recorded.';
COMMENT ON COLUMN ledger.merkle_anchors.external_anchor IS
  'Optional external commitment reference (blockchain tx hash, RFC-3161 token, OpenTimestamps proof URL). Null until externally anchored.';

CREATE INDEX IF NOT EXISTS idx_merkle_anchors_anchored_at ON ledger.merkle_anchors (anchored_at);
CREATE INDEX IF NOT EXISTS idx_merkle_anchors_to_seq      ON ledger.merkle_anchors (to_seq);

-- ----------------------------------------------------------------------------
-- Trigger function: hash-chain on INSERT.
-- Computes payload_hash, pulls prev_hash from the prior row (by seq), derives
-- entry_hash. Any client-supplied values for these columns are overwritten.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION ledger.action_events_hash_chain()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_prev_hash char(64);
  v_genesis   char(64) := repeat('0', 64);
BEGIN
  -- Compute the payload hash from the canonicalised payload.
  NEW.payload_hash := public.admatix_sha256_jsonb(NEW.payload);

  -- Pull prev_hash from the most recent row by seq. NEW.seq is already assigned
  -- because the bigserial DEFAULT is evaluated before BEFORE-INSERT triggers.
  SELECT ae.entry_hash
    INTO v_prev_hash
    FROM ledger.action_events ae
   WHERE ae.seq < NEW.seq
   ORDER BY ae.seq DESC
   LIMIT 1;

  NEW.prev_hash := COALESCE(v_prev_hash, v_genesis);

  -- Derive entry_hash from the immutable chain material.
  NEW.entry_hash := public.admatix_sha256_text(
       NEW.prev_hash
    || '|' || NEW.event_id
    || '|' || NEW.tx_id
    || '|' || NEW.event_type::text
    || '|' || NEW.step::text
    || '|' || NEW.payload_hash
    || '|' || to_char(NEW.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
  );

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION ledger.action_events_hash_chain() IS
  'BEFORE INSERT trigger on ledger.action_events. Computes payload_hash, sets prev_hash from the previous row by seq (genesis = 64 zeros), and derives entry_hash over the immutable chain material. Client-supplied hash columns are overwritten.';

DROP TRIGGER IF EXISTS trg_action_events_hash_chain ON ledger.action_events;
CREATE TRIGGER trg_action_events_hash_chain
  BEFORE INSERT ON ledger.action_events
  FOR EACH ROW
  EXECUTE FUNCTION ledger.action_events_hash_chain();

COMMENT ON TRIGGER trg_action_events_hash_chain ON ledger.action_events IS
  'Maintains the tamper-evident hash chain on every INSERT.';

-- ----------------------------------------------------------------------------
-- Trigger function: block UPDATE and DELETE on the ledger. Defence in depth
-- alongside the REVOKE statements below.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION ledger.reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION
    'ledger.% is append-only: % is not permitted', TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'restrict_violation',
          HINT = 'Ledger rows are immutable. Append a corrective event instead.';
  RETURN NULL;
END;
$$;

COMMENT ON FUNCTION ledger.reject_mutation() IS
  'Trigger function that unconditionally raises on UPDATE/DELETE/TRUNCATE. Enforces ledger immutability even if table privileges are misconfigured.';

DROP TRIGGER IF EXISTS trg_action_events_no_update ON ledger.action_events;
CREATE TRIGGER trg_action_events_no_update
  BEFORE UPDATE ON ledger.action_events
  FOR EACH ROW EXECUTE FUNCTION ledger.reject_mutation();

DROP TRIGGER IF EXISTS trg_action_events_no_delete ON ledger.action_events;
CREATE TRIGGER trg_action_events_no_delete
  BEFORE DELETE ON ledger.action_events
  FOR EACH ROW EXECUTE FUNCTION ledger.reject_mutation();

DROP TRIGGER IF EXISTS trg_action_events_no_truncate ON ledger.action_events;
CREATE TRIGGER trg_action_events_no_truncate
  BEFORE TRUNCATE ON ledger.action_events
  FOR EACH STATEMENT EXECUTE FUNCTION ledger.reject_mutation();

DROP TRIGGER IF EXISTS trg_merkle_anchors_no_update ON ledger.merkle_anchors;
CREATE TRIGGER trg_merkle_anchors_no_update
  BEFORE UPDATE ON ledger.merkle_anchors
  FOR EACH ROW EXECUTE FUNCTION ledger.reject_mutation();

DROP TRIGGER IF EXISTS trg_merkle_anchors_no_delete ON ledger.merkle_anchors;
CREATE TRIGGER trg_merkle_anchors_no_delete
  BEFORE DELETE ON ledger.merkle_anchors
  FOR EACH ROW EXECUTE FUNCTION ledger.reject_mutation();

COMMENT ON TRIGGER trg_action_events_no_update ON ledger.action_events IS
  'Blocks all UPDATE statements: ledger rows are immutable.';
COMMENT ON TRIGGER trg_action_events_no_delete ON ledger.action_events IS
  'Blocks all DELETE statements: ledger rows are immutable.';

-- ----------------------------------------------------------------------------
-- Privileges: grant append + read only. Revoke UPDATE/DELETE/TRUNCATE.
-- ----------------------------------------------------------------------------
GRANT USAGE ON SCHEMA ledger TO admatix_app, admatix_readonly;

GRANT SELECT, INSERT ON ledger.action_events  TO admatix_app;
GRANT SELECT, INSERT ON ledger.merkle_anchors TO admatix_app;
GRANT SELECT          ON ledger.action_events  TO admatix_readonly;
GRANT SELECT          ON ledger.merkle_anchors TO admatix_readonly;

-- The bigserial / identity sequences must be usable by the app role for INSERT.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ledger TO admatix_app;

-- Explicitly revoke the mutating privileges. The UPDATE/DELETE triggers above
-- are belt-and-braces in case a future GRANT accidentally re-adds these.
REVOKE UPDATE, DELETE, TRUNCATE ON ledger.action_events  FROM admatix_app, admatix_readonly, PUBLIC;
REVOKE UPDATE, DELETE, TRUNCATE ON ledger.merkle_anchors FROM admatix_app, admatix_readonly, PUBLIC;

COMMIT;
