from __future__ import annotations

import csv
import gzip
import json
import sys
from dataclasses import replace
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from admatix_ingest import (  # noqa: E402
    CRITEO_UPLIFT_SPEC,
    HILLSTROM_SPEC,
    DatasetIntegrityError,
    DatasetSpec,
    acquire_dataset,
    compute_sha256,
    download_to_raw,
    validate_dataset,
    write_checksum_record,
)


def _write_csv(path: Path, header: list[str], rows: list[list[object]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def _strip_pinned_hashes(spec: DatasetSpec) -> DatasetSpec:
    """Drop the pinned hashes so synthetic fixtures don't trip integrity checks.

    Production specs ship with pinned expected_*_sha256 values to abort on
    upstream tampering (finding #7); tests work with locally-generated bytes
    that obviously won't match those hashes, so the test spec strips them.
    """
    return replace(spec, expected_archive_sha256=None, expected_landed_sha256=None)


def test_hillstrom_schema_checksum_and_manifest(tmp_path: Path) -> None:
    source = tmp_path / "hillstrom.csv"
    _write_csv(
        source,
        HILLSTROM_SPEC.columns,
        [
            [1, "$0 - $100", 83.0, 1, 0, "Urban", 0, "Phone", "No E-Mail", 0, 0, 0.0],
            [4, "$100 - $200", 128.5, 0, 1, "Rural", 1, "Web", "Mens E-Mail", 1, 1, 42.5],
        ],
    )

    spec = _strip_pinned_hashes(HILLSTROM_SPEC)
    result = acquire_dataset(
        spec,
        source,
        tmp_path / "datasets",
        tmp_path / "checksums",
        enforce_expected_rows=False,
    )

    assert result.dataset == "hillstrom"
    assert result.rows == 2
    assert result.landed_path == tmp_path / "datasets" / "hillstrom" / "hillstrom.csv"
    # sha256 now reflects the LANDED file (not the source). For Hillstrom
    # source and landed are identical CSV bytes so the hashes match.
    assert result.sha256 == compute_sha256(result.landed_path)
    assert result.sha256 == compute_sha256(source)
    assert result.archive_sha256 == compute_sha256(source)
    assert result.schema_ok is True
    assert (tmp_path / "checksums" / "hillstrom.sha256").read_text(encoding="utf-8").startswith(result.sha256)
    manifest = json.loads((tmp_path / "checksums" / "hillstrom.manifest.json").read_text(encoding="utf-8"))
    assert manifest["license"] == HILLSTROM_SPEC.license
    assert manifest["redistribution"] == "permissive_with_attribution_recommended"
    assert manifest["sha256"] == result.sha256
    assert manifest["archive_sha256"] == result.archive_sha256
    assert manifest["landed_filename"] == "hillstrom.csv"


def test_criteo_uplift_gzip_lands_decompressed_and_validates_schema(tmp_path: Path) -> None:
    csv_path = tmp_path / "criteo-uplift-v2.1.csv"
    rows = [
        [0.1] * 12 + [1, 0, 1, 1],
        [0.2] * 12 + [0, 0, 0, 0],
    ]
    _write_csv(csv_path, CRITEO_UPLIFT_SPEC.columns, rows)
    source = tmp_path / "criteo-uplift-v2.1.csv.gz"
    with csv_path.open("rb") as raw, gzip.open(source, "wb") as compressed:
        compressed.write(raw.read())

    spec = _strip_pinned_hashes(CRITEO_UPLIFT_SPEC)
    result = acquire_dataset(
        spec,
        source,
        tmp_path / "datasets",
        tmp_path / "checksums",
        enforce_expected_rows=False,
    )

    assert result.dataset == "criteo_uplift_v2.1"
    assert result.rows == 2
    assert result.compressed is True
    assert result.landed_path.name == "criteo-uplift-v2.1.csv"
    assert result.landed_path.exists()
    assert validate_dataset(CRITEO_UPLIFT_SPEC, result.landed_path).schema_ok is True
    # sha256 must be the LANDED CSV hash, NOT the .gz archive hash (finding #6).
    assert result.sha256 == compute_sha256(result.landed_path)
    assert result.sha256 != compute_sha256(source)
    assert result.archive_sha256 == compute_sha256(source)
    manifest = json.loads((tmp_path / "checksums" / "criteo_uplift_v2.1.manifest.json").read_text(encoding="utf-8"))
    assert manifest["redistribution"] == "internal_non_commercial_only"
    assert manifest["sha256"] == compute_sha256(result.landed_path)
    assert manifest["archive_sha256"] == compute_sha256(source)
    assert manifest["landed_filename"] == "criteo-uplift-v2.1.csv"
    assert manifest["archive_filename"] == "criteo-uplift-v2.1.csv.gz"
    # The checksum file is keyed on the LANDED filename so `sha256sum -c` in
    # data/datasets validates the bytes the simulator/verifier actually reads.
    checksum_line = (tmp_path / "checksums" / "criteo_uplift_v2.1.sha256").read_text(encoding="utf-8")
    assert checksum_line.strip().endswith("criteo-uplift-v2.1.csv")


def test_schema_rejects_missing_or_misordered_columns(tmp_path: Path) -> None:
    source = tmp_path / "bad.csv"
    _write_csv(source, ["segment", "visit"], [["No E-Mail", 0]])

    result = validate_dataset(HILLSTROM_SPEC, source)

    assert result.schema_ok is False
    assert "expected 12 columns" in result.reason


def test_write_checksum_record_is_stable_and_git_safe(tmp_path: Path) -> None:
    artifact = tmp_path / "artifact.csv"
    artifact.write_text("a,b\n1,2\n", encoding="utf-8")
    spec = DatasetSpec(
        name="tiny",
        source_url="https://example.invalid/tiny.csv",
        license="test-only",
        redistribution="permissive_with_attribution_recommended",
        columns=["a", "b"],
        expected_rows=None,
        compressed=False,
        output_filename="tiny.csv",
    )

    record = write_checksum_record(spec, artifact, tmp_path / "checksums", rows=1, schema_ok=True)

    assert record.sha256 == compute_sha256(artifact)
    assert record.checksum_path.name == "tiny.sha256"
    assert record.manifest_path.name == "tiny.manifest.json"
    assert "data/datasets" not in record.manifest_path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Regression tests for findings #6, #7, #8.
# ---------------------------------------------------------------------------


def test_acquire_dataset_aborts_on_archive_hash_mismatch(tmp_path: Path) -> None:
    """Finding #7: a spec with a pinned expected_archive_sha256 must abort
    when the source bytes don't match — silent re-recording is what allowed
    bit-rot / MITM to land undetected.
    """
    source = tmp_path / "hillstrom.csv"
    _write_csv(
        source,
        HILLSTROM_SPEC.columns,
        [[1, "$0 - $100", 83.0, 1, 0, "Urban", 0, "Phone", "No E-Mail", 0, 0, 0.0]],
    )
    pinned_spec = replace(
        HILLSTROM_SPEC,
        expected_archive_sha256="0" * 64,
        expected_landed_sha256=None,
    )
    try:
        acquire_dataset(
            pinned_spec,
            source,
            tmp_path / "datasets",
            tmp_path / "checksums",
            enforce_expected_rows=False,
        )
    except DatasetIntegrityError as exc:
        assert "archive sha256 mismatch" in str(exc)
        return
    raise AssertionError("acquire_dataset must raise DatasetIntegrityError on hash mismatch")


def test_acquire_dataset_aborts_on_landed_hash_mismatch(tmp_path: Path) -> None:
    """Finding #6: the LANDED file is what downstream code reads. A pinned
    expected_landed_sha256 must be enforced after decompression, not just on
    the upstream archive.
    """
    source = tmp_path / "hillstrom.csv"
    _write_csv(
        source,
        HILLSTROM_SPEC.columns,
        [[1, "$0 - $100", 83.0, 1, 0, "Urban", 0, "Phone", "No E-Mail", 0, 0, 0.0]],
    )
    pinned_spec = replace(
        HILLSTROM_SPEC,
        expected_archive_sha256=None,
        expected_landed_sha256="0" * 64,
    )
    try:
        acquire_dataset(
            pinned_spec,
            source,
            tmp_path / "datasets",
            tmp_path / "checksums",
            enforce_expected_rows=False,
        )
    except DatasetIntegrityError as exc:
        assert "landed sha256 mismatch" in str(exc)
        return
    raise AssertionError("acquire_dataset must raise DatasetIntegrityError on landed hash mismatch")


def test_download_to_raw_rejects_corrupt_cache_when_hash_is_pinned(tmp_path: Path) -> None:
    """Finding #8: a non-empty but corrupt cached file was previously trusted
    forever. With a pinned hash, the corrupted cache must be replaced.
    """
    spec = replace(
        HILLSTROM_SPEC,
        # Use a file:// URL so we don't actually hit the network from a test.
        source_url=(tmp_path / "fake-source.csv").as_uri(),
        expected_archive_sha256="dead" + "0" * 60,
        expected_landed_sha256=None,
    )
    # Seed a corrupt cache file at the path download_to_raw would write to.
    raw_dir = tmp_path / "raw" / spec.name
    raw_dir.mkdir(parents=True)
    cached = raw_dir / Path(spec.source_url).name
    cached.write_bytes(b"truncated junk that is the wrong bytes")
    assert cached.stat().st_size > 0

    # No source file at the URL; if the cache were trusted, download_to_raw
    # would happily return it. With the hash pin, it must reject and re-fetch
    # (which then fails because the URL doesn't exist) — either way the
    # corrupt bytes never propagate. We assert it does NOT return a hash-
    # mismatching cached path.
    try:
        result = download_to_raw(spec, tmp_path / "raw")
    except (DatasetIntegrityError, OSError, urllib_error_subclass()):
        # Acceptable: re-fetch attempted and failed because URL is fake.
        return
    raise AssertionError(
        f"download_to_raw silently trusted a corrupt cache: returned {result}"
    )


def urllib_error_subclass():  # pragma: no cover - tiny helper for the except above
    import urllib.error

    return urllib.error.URLError
